import type { ScenarioInput } from "./types";

export const EMPTY_SCENARIO: ScenarioInput = {
  vehicle: {
    name: "",
    originalPrice: 0,
    dealerDiscount: 0,
    discountAppliesTo: "none",
    selectedOptions: [],
  },
  bank: {
    bankName: "",
    downPayment: 0,
    loanAmount: 0,
    termMonths: 36,
    monthlyAmortization: 0,
    paymentType: "oma",
    chattelMortgage: 0,
    bankFees: 0,
    docStampTax: 0,
    notarial: 0,
    ltoEncumbrance: 0,
    registration: 0,
    comprehensiveInsurance: 0,
    ctpl: 0,
    otherFees: 0,
    promoNotes: "",
  },
  c2c: {
    providerName: "",
    loanableAmount: 0,
    termMonths: 36,
    monthlyAddOnRate: 0,
    eirpa: 0,
    monthlyPaymentOverride: 0,
    processingFee: 0,
    registration: 0,
    comprehensiveInsurance: 0,
    ctpl: 0,
    otherFees: 0,
    promoNotes: "",
  },
  inHouse: {
    dealerName: "",
    downPayment: 0,
    loanAmount: 0,
    termMonths: 36,
    monthlyAmortization: 0,
    paymentType: "oma",
    chattelMortgage: 0,
    processingFee: 0,
    documentationFee: 0,
    registration: 0,
    comprehensiveInsurance: 0,
    ctpl: 0,
    otherFees: 0,
    promoNotes: "",
  },
};

// Sample: Toyota Yaris Cross 2026 (from the user's spec)
export const SAMPLE_SCENARIO: ScenarioInput = {
  vehicle: {
    name: "Toyota Yaris Cross 2026",
    originalPrice: 1_690_000,
    dealerDiscount: 90_000,
    discountAppliesTo: "all",
    selectedOptions: [],
  },
  bank: {
    bankName: "BPI",
    downPayment: 507_000,
    loanAmount: 1_183_000,
    termMonths: 36,
    monthlyAmortization: 38_369,
    paymentType: "oma",
    chattelMortgage: 0,
    bankFees: 0,
    docStampTax: 0,
    notarial: 0,
    ltoEncumbrance: 0,
    registration: 0,
    comprehensiveInsurance: 0,
    ctpl: 0,
    otherFees: 0,
    promoNotes: "36-month term does not qualify for 60-month promo freebies.",
  },
  c2c: {
    providerName: "",
    loanableAmount: 1_090_000,
    termMonths: 36,
    monthlyAddOnRate: 0.59,
    eirpa: 12.97,
    monthlyPaymentOverride: 0,
    processingFee: 0,
    registration: 0,
    comprehensiveInsurance: 0,
    ctpl: 0,
    otherFees: 0,
    promoNotes: "No chattel mortgage — treated as a cash purchase.",
  },
  inHouse: {
    dealerName: "",
    downPayment: 0,
    loanAmount: 0,
    termMonths: 36,
    monthlyAmortization: 0,
    paymentType: "oma",
    chattelMortgage: 0,
    processingFee: 0,
    documentationFee: 0,
    registration: 0,
    comprehensiveInsurance: 0,
    ctpl: 0,
    otherFees: 0,
    promoNotes: "",
  },
};
